"""
AI RMF Baseline OSCAL profile generator (v0.3).

Emits profiles/ai-rmf-baseline-profile.json. Imports the community AI RMF
v0.3 catalog (all 72 controls, include-all). Released under CC0 1.0.

The profile demonstrates the simplest valid pattern: import the catalog,
select all controls, merge as-is. Downstream consumers can derive narrower
profiles by replacing `include-all` with `include-controls` or adding
`exclude-controls`.

UUIDs are deterministic uuid5 from the project namespace so that
regeneration produces stable output.

Usage:
    python3 src/profile_generator.py
"""

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO / "profiles" / "ai-rmf-baseline-profile.json"

NAMESPACE_OID = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")  # url namespace per RFC 4122
ATR_OSCAL_NS = uuid.uuid5(NAMESPACE_OID, "https://github.com/Agent-Threat-Rule/ai-rmf-oscal-catalog")


def stable_uuid(seed: str) -> str:
    return str(uuid.uuid5(ATR_OSCAL_NS, seed))


def preserved_last_modified(new_doc: dict) -> str:
    fresh = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    if not OUTPUT_PATH.exists():
        return fresh
    try:
        with OUTPUT_PATH.open() as f:
            existing = json.load(f)
    except (OSError, json.JSONDecodeError):
        return fresh

    def stripped(doc: dict) -> dict:
        prof = dict(doc.get("profile", {}))
        meta = dict(prof.get("metadata", {}))
        meta.pop("last-modified", None)
        prof["metadata"] = meta
        return {"profile": prof}

    if stripped(existing) == stripped(new_doc):
        return existing.get("profile", {}).get("metadata", {}).get("last-modified", fresh)
    return fresh


def build_profile() -> dict:
    catalog_resource_uuid = stable_uuid("profile-catalog-resource:ai-rmf-v0.3")
    party_uuid = stable_uuid("profile-party:community")

    profile = {
        "uuid": stable_uuid("profile:ai-rmf-baseline-v0.3"),
        "metadata": {
            "title": "AI RMF Baseline Profile (community example)",
            "last-modified": "PLACEHOLDER",
            "version": "0.3.0",
            "oscal-version": "1.2.2",
            "parties": [
                {
                    "uuid": party_uuid,
                    "type": "organization",
                    "name": "ai-rmf-oscal-catalog community contributors",
                    "remarks": (
                        "Community contributors to the ai-rmf-oscal-catalog project. "
                        "Not produced by, endorsed by, or affiliated with NIST."
                    ),
                },
            ],
            "remarks": (
                "A minimal OSCAL profile that imports the community AI RMF v0.3 "
                "catalog and selects all 72 subcategory controls. This profile is "
                "a worked example demonstrating how the catalog is consumed by "
                "downstream tooling, not an opinionated baseline for any particular "
                "sector, risk posture, or compliance regime. Downstream profiles "
                "deriving narrower selections (e.g., GOVERN-only, or skipping "
                "MEASURE 2.12 environmental impact in contexts where it is out of "
                "scope) should replace `include-all` with `include-controls` or "
                "add `exclude-controls`. Released under CC0 1.0."
            ),
        },
        "imports": [
            {
                "href": f"#{catalog_resource_uuid}",
                "include-all": {},
            },
        ],
        "merge": {
            "as-is": True,
        },
        "back-matter": {
            "resources": [
                {
                    "uuid": catalog_resource_uuid,
                    "title": "AI RMF community OSCAL catalog (v0.3)",
                    "description": (
                        "Resolves to the v0.3 catalog generated by src/generator.py "
                        "from this repository. Two rlinks are provided: the canonical "
                        "HTTPS URL on GitHub for production use, and a relative "
                        "filesystem path for local validation runs."
                    ),
                    "rlinks": [
                        {
                            "href": "https://raw.githubusercontent.com/Agent-Threat-Rule/ai-rmf-oscal-catalog/main/catalogs/ai-rmf-v0.3.json",
                        },
                        {
                            "href": "../catalogs/ai-rmf-v0.3.json",
                        },
                    ],
                    "remarks": (
                        "First rlink is preferred when validating from outside this "
                        "repository. Second rlink works when validating from inside "
                        "the repo (relative to profiles/)."
                    ),
                },
            ],
        },
    }

    document = {"profile": profile}
    profile["metadata"]["last-modified"] = preserved_last_modified(document)
    return document


def main() -> int:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    profile = build_profile()
    with OUTPUT_PATH.open("w") as f:
        json.dump(profile, f, indent=2, ensure_ascii=False)
    p = profile["profile"]
    print(f"wrote {OUTPUT_PATH}")
    print(f"  profile uuid:        {p['uuid']}")
    print(f"  imports (catalog):   {p['imports'][0]['href']}")
    print(f"  selection:           include-all")
    print(f"  last-modified:       {p['metadata']['last-modified']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
